# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import BuildingInfo_pb2 as BuildingInfo__pb2


class PyRLServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getRewards = channel.unary_unary(
        '/PyRLServer.PyRLServer/getRewards',
        request_serializer=BuildingInfo__pb2.Empty.SerializeToString,
        response_deserializer=BuildingInfo__pb2.Reward.FromString,
        )


class PyRLServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getRewards(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PyRLServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getRewards': grpc.unary_unary_rpc_method_handler(
          servicer.getRewards,
          request_deserializer=BuildingInfo__pb2.Empty.FromString,
          response_serializer=BuildingInfo__pb2.Reward.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PyRLServer.PyRLServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
