# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BuildingInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BuildingInfo.proto',
  package='PyRLServer',
  syntax='proto3',
  serialized_options=_b('\n\nPyRLServerB\tPyRLProto'),
  serialized_pb=_b('\n\x12\x42uildingInfo.proto\x12\nPyRLServer\"\x07\n\x05\x45mpty\"\x18\n\x06Reward\x12\x0e\n\x06reward\x18\x01 \x01(\x01\x32\x43\n\nPyRLServer\x12\x35\n\ngetRewards\x12\x11.PyRLServer.Empty\x1a\x12.PyRLServer.Reward\"\x00\x42\x17\n\nPyRLServerB\tPyRLProtob\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='PyRLServer.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=41,
)


_REWARD = _descriptor.Descriptor(
  name='Reward',
  full_name='PyRLServer.Reward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reward', full_name='PyRLServer.Reward.reward', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Reward'] = _REWARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'BuildingInfo_pb2'
  # @@protoc_insertion_point(class_scope:PyRLServer.Empty)
  })
_sym_db.RegisterMessage(Empty)

Reward = _reflection.GeneratedProtocolMessageType('Reward', (_message.Message,), {
  'DESCRIPTOR' : _REWARD,
  '__module__' : 'BuildingInfo_pb2'
  # @@protoc_insertion_point(class_scope:PyRLServer.Reward)
  })
_sym_db.RegisterMessage(Reward)


DESCRIPTOR._options = None

_PYRLSERVER = _descriptor.ServiceDescriptor(
  name='PyRLServer',
  full_name='PyRLServer.PyRLServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=69,
  serialized_end=136,
  methods=[
  _descriptor.MethodDescriptor(
    name='getRewards',
    full_name='PyRLServer.PyRLServer.getRewards',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_REWARD,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PYRLSERVER)

DESCRIPTOR.services_by_name['PyRLServer'] = _PYRLSERVER

# @@protoc_insertion_point(module_scope)
