// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AgentInfo.proto

package PyRLAgent;

public final class PyRLProto {
  private PyRLProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AgentInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PyRLAgent.AgentInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    java.util.List<PyRLProto.Agent> 
        getAgentsList();
    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    PyRLProto.Agent getAgents(int index);
    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    int getAgentsCount();
    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    java.util.List<? extends PyRLProto.AgentOrBuilder> 
        getAgentsOrBuilderList();
    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    PyRLProto.AgentOrBuilder getAgentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PyRLAgent.AgentInfo}
   */
  public  static final class AgentInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PyRLAgent.AgentInfo)
      AgentInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AgentInfo.newBuilder() to construct.
    private AgentInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AgentInfo() {
      agents_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AgentInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AgentInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                agents_ = new java.util.ArrayList<PyRLProto.Agent>();
                mutable_bitField0_ |= 0x00000001;
              }
              agents_.add(
                  input.readMessage(PyRLProto.Agent.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          agents_ = java.util.Collections.unmodifiableList(agents_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PyRLProto.internal_static_PyRLAgent_AgentInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PyRLProto.internal_static_PyRLAgent_AgentInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PyRLProto.AgentInfo.class, PyRLProto.AgentInfo.Builder.class);
    }

    public static final int AGENTS_FIELD_NUMBER = 1;
    private java.util.List<PyRLProto.Agent> agents_;
    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    public java.util.List<PyRLProto.Agent> getAgentsList() {
      return agents_;
    }
    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    public java.util.List<? extends PyRLProto.AgentOrBuilder> 
        getAgentsOrBuilderList() {
      return agents_;
    }
    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    public int getAgentsCount() {
      return agents_.size();
    }
    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    public PyRLProto.Agent getAgents(int index) {
      return agents_.get(index);
    }
    /**
     * <code>repeated .PyRLAgent.Agent agents = 1;</code>
     */
    public PyRLProto.AgentOrBuilder getAgentsOrBuilder(
        int index) {
      return agents_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < agents_.size(); i++) {
        output.writeMessage(1, agents_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < agents_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, agents_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PyRLProto.AgentInfo)) {
        return super.equals(obj);
      }
      PyRLProto.AgentInfo other = (PyRLProto.AgentInfo) obj;

      if (!getAgentsList()
          .equals(other.getAgentsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAgentsCount() > 0) {
        hash = (37 * hash) + AGENTS_FIELD_NUMBER;
        hash = (53 * hash) + getAgentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PyRLProto.AgentInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.AgentInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.AgentInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.AgentInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.AgentInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.AgentInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.AgentInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PyRLProto.AgentInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PyRLProto.AgentInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PyRLProto.AgentInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PyRLProto.AgentInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PyRLProto.AgentInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PyRLProto.AgentInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PyRLAgent.AgentInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PyRLAgent.AgentInfo)
        PyRLProto.AgentInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PyRLProto.internal_static_PyRLAgent_AgentInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PyRLProto.internal_static_PyRLAgent_AgentInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PyRLProto.AgentInfo.class, PyRLProto.AgentInfo.Builder.class);
      }

      // Construct using PyRLProto.AgentInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAgentsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (agentsBuilder_ == null) {
          agents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          agentsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PyRLProto.internal_static_PyRLAgent_AgentInfo_descriptor;
      }

      @java.lang.Override
      public PyRLProto.AgentInfo getDefaultInstanceForType() {
        return PyRLProto.AgentInfo.getDefaultInstance();
      }

      @java.lang.Override
      public PyRLProto.AgentInfo build() {
        PyRLProto.AgentInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PyRLProto.AgentInfo buildPartial() {
        PyRLProto.AgentInfo result = new PyRLProto.AgentInfo(this);
        int from_bitField0_ = bitField0_;
        if (agentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            agents_ = java.util.Collections.unmodifiableList(agents_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.agents_ = agents_;
        } else {
          result.agents_ = agentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PyRLProto.AgentInfo) {
          return mergeFrom((PyRLProto.AgentInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PyRLProto.AgentInfo other) {
        if (other == PyRLProto.AgentInfo.getDefaultInstance()) return this;
        if (agentsBuilder_ == null) {
          if (!other.agents_.isEmpty()) {
            if (agents_.isEmpty()) {
              agents_ = other.agents_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAgentsIsMutable();
              agents_.addAll(other.agents_);
            }
            onChanged();
          }
        } else {
          if (!other.agents_.isEmpty()) {
            if (agentsBuilder_.isEmpty()) {
              agentsBuilder_.dispose();
              agentsBuilder_ = null;
              agents_ = other.agents_;
              bitField0_ = (bitField0_ & ~0x00000001);
              agentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAgentsFieldBuilder() : null;
            } else {
              agentsBuilder_.addAllMessages(other.agents_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PyRLProto.AgentInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PyRLProto.AgentInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PyRLProto.Agent> agents_ =
        java.util.Collections.emptyList();
      private void ensureAgentsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          agents_ = new java.util.ArrayList<PyRLProto.Agent>(agents_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PyRLProto.Agent, PyRLProto.Agent.Builder, PyRLProto.AgentOrBuilder> agentsBuilder_;

      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public java.util.List<PyRLProto.Agent> getAgentsList() {
        if (agentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(agents_);
        } else {
          return agentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public int getAgentsCount() {
        if (agentsBuilder_ == null) {
          return agents_.size();
        } else {
          return agentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public PyRLProto.Agent getAgents(int index) {
        if (agentsBuilder_ == null) {
          return agents_.get(index);
        } else {
          return agentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public Builder setAgents(
          int index, PyRLProto.Agent value) {
        if (agentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgentsIsMutable();
          agents_.set(index, value);
          onChanged();
        } else {
          agentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public Builder setAgents(
          int index, PyRLProto.Agent.Builder builderForValue) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          agents_.set(index, builderForValue.build());
          onChanged();
        } else {
          agentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public Builder addAgents(PyRLProto.Agent value) {
        if (agentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgentsIsMutable();
          agents_.add(value);
          onChanged();
        } else {
          agentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public Builder addAgents(
          int index, PyRLProto.Agent value) {
        if (agentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgentsIsMutable();
          agents_.add(index, value);
          onChanged();
        } else {
          agentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public Builder addAgents(
          PyRLProto.Agent.Builder builderForValue) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          agents_.add(builderForValue.build());
          onChanged();
        } else {
          agentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public Builder addAgents(
          int index, PyRLProto.Agent.Builder builderForValue) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          agents_.add(index, builderForValue.build());
          onChanged();
        } else {
          agentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public Builder addAllAgents(
          java.lang.Iterable<? extends PyRLProto.Agent> values) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, agents_);
          onChanged();
        } else {
          agentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public Builder clearAgents() {
        if (agentsBuilder_ == null) {
          agents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          agentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public Builder removeAgents(int index) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          agents_.remove(index);
          onChanged();
        } else {
          agentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public PyRLProto.Agent.Builder getAgentsBuilder(
          int index) {
        return getAgentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public PyRLProto.AgentOrBuilder getAgentsOrBuilder(
          int index) {
        if (agentsBuilder_ == null) {
          return agents_.get(index);  } else {
          return agentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public java.util.List<? extends PyRLProto.AgentOrBuilder> 
           getAgentsOrBuilderList() {
        if (agentsBuilder_ != null) {
          return agentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(agents_);
        }
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public PyRLProto.Agent.Builder addAgentsBuilder() {
        return getAgentsFieldBuilder().addBuilder(
            PyRLProto.Agent.getDefaultInstance());
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public PyRLProto.Agent.Builder addAgentsBuilder(
          int index) {
        return getAgentsFieldBuilder().addBuilder(
            index, PyRLProto.Agent.getDefaultInstance());
      }
      /**
       * <code>repeated .PyRLAgent.Agent agents = 1;</code>
       */
      public java.util.List<PyRLProto.Agent.Builder> 
           getAgentsBuilderList() {
        return getAgentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PyRLProto.Agent, PyRLProto.Agent.Builder, PyRLProto.AgentOrBuilder> 
          getAgentsFieldBuilder() {
        if (agentsBuilder_ == null) {
          agentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PyRLProto.Agent, PyRLProto.Agent.Builder, PyRLProto.AgentOrBuilder>(
                  agents_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          agents_ = null;
        }
        return agentsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PyRLAgent.AgentInfo)
    }

    // @@protoc_insertion_point(class_scope:PyRLAgent.AgentInfo)
    private static final PyRLProto.AgentInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PyRLProto.AgentInfo();
    }

    public static PyRLProto.AgentInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AgentInfo>
        PARSER = new com.google.protobuf.AbstractParser<AgentInfo>() {
      @java.lang.Override
      public AgentInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AgentInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AgentInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AgentInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PyRLProto.AgentInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActionInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PyRLAgent.ActionInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    java.util.List<PyRLProto.Action> 
        getActionsList();
    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    PyRLProto.Action getActions(int index);
    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    int getActionsCount();
    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    java.util.List<? extends PyRLProto.ActionOrBuilder> 
        getActionsOrBuilderList();
    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    PyRLProto.ActionOrBuilder getActionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PyRLAgent.ActionInfo}
   */
  public  static final class ActionInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PyRLAgent.ActionInfo)
      ActionInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActionInfo.newBuilder() to construct.
    private ActionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActionInfo() {
      actions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ActionInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActionInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                actions_ = new java.util.ArrayList<PyRLProto.Action>();
                mutable_bitField0_ |= 0x00000001;
              }
              actions_.add(
                  input.readMessage(PyRLProto.Action.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          actions_ = java.util.Collections.unmodifiableList(actions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PyRLProto.internal_static_PyRLAgent_ActionInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PyRLProto.internal_static_PyRLAgent_ActionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PyRLProto.ActionInfo.class, PyRLProto.ActionInfo.Builder.class);
    }

    public static final int ACTIONS_FIELD_NUMBER = 1;
    private java.util.List<PyRLProto.Action> actions_;
    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    public java.util.List<PyRLProto.Action> getActionsList() {
      return actions_;
    }
    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    public java.util.List<? extends PyRLProto.ActionOrBuilder> 
        getActionsOrBuilderList() {
      return actions_;
    }
    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    public int getActionsCount() {
      return actions_.size();
    }
    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    public PyRLProto.Action getActions(int index) {
      return actions_.get(index);
    }
    /**
     * <code>repeated .PyRLAgent.Action actions = 1;</code>
     */
    public PyRLProto.ActionOrBuilder getActionsOrBuilder(
        int index) {
      return actions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < actions_.size(); i++) {
        output.writeMessage(1, actions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < actions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, actions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PyRLProto.ActionInfo)) {
        return super.equals(obj);
      }
      PyRLProto.ActionInfo other = (PyRLProto.ActionInfo) obj;

      if (!getActionsList()
          .equals(other.getActionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getActionsCount() > 0) {
        hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getActionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PyRLProto.ActionInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.ActionInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.ActionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.ActionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.ActionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.ActionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.ActionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PyRLProto.ActionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PyRLProto.ActionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PyRLProto.ActionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PyRLProto.ActionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PyRLProto.ActionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PyRLProto.ActionInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PyRLAgent.ActionInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PyRLAgent.ActionInfo)
        PyRLProto.ActionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PyRLProto.internal_static_PyRLAgent_ActionInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PyRLProto.internal_static_PyRLAgent_ActionInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PyRLProto.ActionInfo.class, PyRLProto.ActionInfo.Builder.class);
      }

      // Construct using PyRLProto.ActionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getActionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (actionsBuilder_ == null) {
          actions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          actionsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PyRLProto.internal_static_PyRLAgent_ActionInfo_descriptor;
      }

      @java.lang.Override
      public PyRLProto.ActionInfo getDefaultInstanceForType() {
        return PyRLProto.ActionInfo.getDefaultInstance();
      }

      @java.lang.Override
      public PyRLProto.ActionInfo build() {
        PyRLProto.ActionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PyRLProto.ActionInfo buildPartial() {
        PyRLProto.ActionInfo result = new PyRLProto.ActionInfo(this);
        int from_bitField0_ = bitField0_;
        if (actionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            actions_ = java.util.Collections.unmodifiableList(actions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.actions_ = actions_;
        } else {
          result.actions_ = actionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PyRLProto.ActionInfo) {
          return mergeFrom((PyRLProto.ActionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PyRLProto.ActionInfo other) {
        if (other == PyRLProto.ActionInfo.getDefaultInstance()) return this;
        if (actionsBuilder_ == null) {
          if (!other.actions_.isEmpty()) {
            if (actions_.isEmpty()) {
              actions_ = other.actions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureActionsIsMutable();
              actions_.addAll(other.actions_);
            }
            onChanged();
          }
        } else {
          if (!other.actions_.isEmpty()) {
            if (actionsBuilder_.isEmpty()) {
              actionsBuilder_.dispose();
              actionsBuilder_ = null;
              actions_ = other.actions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              actionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getActionsFieldBuilder() : null;
            } else {
              actionsBuilder_.addAllMessages(other.actions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PyRLProto.ActionInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PyRLProto.ActionInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PyRLProto.Action> actions_ =
        java.util.Collections.emptyList();
      private void ensureActionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          actions_ = new java.util.ArrayList<PyRLProto.Action>(actions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PyRLProto.Action, PyRLProto.Action.Builder, PyRLProto.ActionOrBuilder> actionsBuilder_;

      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public java.util.List<PyRLProto.Action> getActionsList() {
        if (actionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(actions_);
        } else {
          return actionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public int getActionsCount() {
        if (actionsBuilder_ == null) {
          return actions_.size();
        } else {
          return actionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public PyRLProto.Action getActions(int index) {
        if (actionsBuilder_ == null) {
          return actions_.get(index);
        } else {
          return actionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public Builder setActions(
          int index, PyRLProto.Action value) {
        if (actionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionsIsMutable();
          actions_.set(index, value);
          onChanged();
        } else {
          actionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public Builder setActions(
          int index, PyRLProto.Action.Builder builderForValue) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.set(index, builderForValue.build());
          onChanged();
        } else {
          actionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public Builder addActions(PyRLProto.Action value) {
        if (actionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionsIsMutable();
          actions_.add(value);
          onChanged();
        } else {
          actionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public Builder addActions(
          int index, PyRLProto.Action value) {
        if (actionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionsIsMutable();
          actions_.add(index, value);
          onChanged();
        } else {
          actionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public Builder addActions(
          PyRLProto.Action.Builder builderForValue) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.add(builderForValue.build());
          onChanged();
        } else {
          actionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public Builder addActions(
          int index, PyRLProto.Action.Builder builderForValue) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.add(index, builderForValue.build());
          onChanged();
        } else {
          actionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public Builder addAllActions(
          java.lang.Iterable<? extends PyRLProto.Action> values) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, actions_);
          onChanged();
        } else {
          actionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public Builder clearActions() {
        if (actionsBuilder_ == null) {
          actions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          actionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public Builder removeActions(int index) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.remove(index);
          onChanged();
        } else {
          actionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public PyRLProto.Action.Builder getActionsBuilder(
          int index) {
        return getActionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public PyRLProto.ActionOrBuilder getActionsOrBuilder(
          int index) {
        if (actionsBuilder_ == null) {
          return actions_.get(index);  } else {
          return actionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public java.util.List<? extends PyRLProto.ActionOrBuilder> 
           getActionsOrBuilderList() {
        if (actionsBuilder_ != null) {
          return actionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(actions_);
        }
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public PyRLProto.Action.Builder addActionsBuilder() {
        return getActionsFieldBuilder().addBuilder(
            PyRLProto.Action.getDefaultInstance());
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public PyRLProto.Action.Builder addActionsBuilder(
          int index) {
        return getActionsFieldBuilder().addBuilder(
            index, PyRLProto.Action.getDefaultInstance());
      }
      /**
       * <code>repeated .PyRLAgent.Action actions = 1;</code>
       */
      public java.util.List<PyRLProto.Action.Builder> 
           getActionsBuilderList() {
        return getActionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PyRLProto.Action, PyRLProto.Action.Builder, PyRLProto.ActionOrBuilder> 
          getActionsFieldBuilder() {
        if (actionsBuilder_ == null) {
          actionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PyRLProto.Action, PyRLProto.Action.Builder, PyRLProto.ActionOrBuilder>(
                  actions_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          actions_ = null;
        }
        return actionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PyRLAgent.ActionInfo)
    }

    // @@protoc_insertion_point(class_scope:PyRLAgent.ActionInfo)
    private static final PyRLProto.ActionInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PyRLProto.ActionInfo();
    }

    public static PyRLProto.ActionInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActionInfo>
        PARSER = new com.google.protobuf.AbstractParser<ActionInfo>() {
      @java.lang.Override
      public ActionInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActionInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActionInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PyRLProto.ActionInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AgentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PyRLAgent.Agent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 agent_id = 1;</code>
     * @return The agentId.
     */
    int getAgentId();

    /**
     * <code>double x = 2;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>double y = 3;</code>
     * @return The y.
     */
    double getY();

    /**
     * <code>int32 water = 4;</code>
     * @return The water.
     */
    int getWater();

    /**
     * <code>int32 hp = 5;</code>
     * @return The hp.
     */
    int getHp();
  }
  /**
   * Protobuf type {@code PyRLAgent.Agent}
   */
  public  static final class Agent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PyRLAgent.Agent)
      AgentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Agent.newBuilder() to construct.
    private Agent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Agent() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Agent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Agent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              agentId_ = input.readInt32();
              break;
            }
            case 17: {

              x_ = input.readDouble();
              break;
            }
            case 25: {

              y_ = input.readDouble();
              break;
            }
            case 32: {

              water_ = input.readInt32();
              break;
            }
            case 40: {

              hp_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PyRLProto.internal_static_PyRLAgent_Agent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PyRLProto.internal_static_PyRLAgent_Agent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PyRLProto.Agent.class, PyRLProto.Agent.Builder.class);
    }

    public static final int AGENT_ID_FIELD_NUMBER = 1;
    private int agentId_;
    /**
     * <code>int32 agent_id = 1;</code>
     * @return The agentId.
     */
    public int getAgentId() {
      return agentId_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private double x_;
    /**
     * <code>double x = 2;</code>
     * @return The x.
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private double y_;
    /**
     * <code>double y = 3;</code>
     * @return The y.
     */
    public double getY() {
      return y_;
    }

    public static final int WATER_FIELD_NUMBER = 4;
    private int water_;
    /**
     * <code>int32 water = 4;</code>
     * @return The water.
     */
    public int getWater() {
      return water_;
    }

    public static final int HP_FIELD_NUMBER = 5;
    private int hp_;
    /**
     * <code>int32 hp = 5;</code>
     * @return The hp.
     */
    public int getHp() {
      return hp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (agentId_ != 0) {
        output.writeInt32(1, agentId_);
      }
      if (x_ != 0D) {
        output.writeDouble(2, x_);
      }
      if (y_ != 0D) {
        output.writeDouble(3, y_);
      }
      if (water_ != 0) {
        output.writeInt32(4, water_);
      }
      if (hp_ != 0) {
        output.writeInt32(5, hp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (agentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, agentId_);
      }
      if (x_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, x_);
      }
      if (y_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, y_);
      }
      if (water_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, water_);
      }
      if (hp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, hp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PyRLProto.Agent)) {
        return super.equals(obj);
      }
      PyRLProto.Agent other = (PyRLProto.Agent) obj;

      if (getAgentId()
          != other.getAgentId()) return false;
      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
      if (getWater()
          != other.getWater()) return false;
      if (getHp()
          != other.getHp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentId();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (37 * hash) + WATER_FIELD_NUMBER;
      hash = (53 * hash) + getWater();
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + getHp();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PyRLProto.Agent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.Agent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.Agent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.Agent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.Agent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.Agent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.Agent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PyRLProto.Agent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PyRLProto.Agent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PyRLProto.Agent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PyRLProto.Agent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PyRLProto.Agent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PyRLProto.Agent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PyRLAgent.Agent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PyRLAgent.Agent)
        PyRLProto.AgentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PyRLProto.internal_static_PyRLAgent_Agent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PyRLProto.internal_static_PyRLAgent_Agent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PyRLProto.Agent.class, PyRLProto.Agent.Builder.class);
      }

      // Construct using PyRLProto.Agent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        agentId_ = 0;

        x_ = 0D;

        y_ = 0D;

        water_ = 0;

        hp_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PyRLProto.internal_static_PyRLAgent_Agent_descriptor;
      }

      @java.lang.Override
      public PyRLProto.Agent getDefaultInstanceForType() {
        return PyRLProto.Agent.getDefaultInstance();
      }

      @java.lang.Override
      public PyRLProto.Agent build() {
        PyRLProto.Agent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PyRLProto.Agent buildPartial() {
        PyRLProto.Agent result = new PyRLProto.Agent(this);
        result.agentId_ = agentId_;
        result.x_ = x_;
        result.y_ = y_;
        result.water_ = water_;
        result.hp_ = hp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PyRLProto.Agent) {
          return mergeFrom((PyRLProto.Agent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PyRLProto.Agent other) {
        if (other == PyRLProto.Agent.getDefaultInstance()) return this;
        if (other.getAgentId() != 0) {
          setAgentId(other.getAgentId());
        }
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        if (other.getWater() != 0) {
          setWater(other.getWater());
        }
        if (other.getHp() != 0) {
          setHp(other.getHp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PyRLProto.Agent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PyRLProto.Agent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int agentId_ ;
      /**
       * <code>int32 agent_id = 1;</code>
       * @return The agentId.
       */
      public int getAgentId() {
        return agentId_;
      }
      /**
       * <code>int32 agent_id = 1;</code>
       * @param value The agentId to set.
       * @return This builder for chaining.
       */
      public Builder setAgentId(int value) {
        
        agentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 agent_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgentId() {
        
        agentId_ = 0;
        onChanged();
        return this;
      }

      private double x_ ;
      /**
       * <code>double x = 2;</code>
       * @return The x.
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 2;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 3;</code>
       * @return The y.
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 3;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0D;
        onChanged();
        return this;
      }

      private int water_ ;
      /**
       * <code>int32 water = 4;</code>
       * @return The water.
       */
      public int getWater() {
        return water_;
      }
      /**
       * <code>int32 water = 4;</code>
       * @param value The water to set.
       * @return This builder for chaining.
       */
      public Builder setWater(int value) {
        
        water_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 water = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWater() {
        
        water_ = 0;
        onChanged();
        return this;
      }

      private int hp_ ;
      /**
       * <code>int32 hp = 5;</code>
       * @return The hp.
       */
      public int getHp() {
        return hp_;
      }
      /**
       * <code>int32 hp = 5;</code>
       * @param value The hp to set.
       * @return This builder for chaining.
       */
      public Builder setHp(int value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHp() {
        
        hp_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PyRLAgent.Agent)
    }

    // @@protoc_insertion_point(class_scope:PyRLAgent.Agent)
    private static final PyRLProto.Agent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PyRLProto.Agent();
    }

    public static PyRLProto.Agent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Agent>
        PARSER = new com.google.protobuf.AbstractParser<Agent>() {
      @java.lang.Override
      public Agent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Agent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Agent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Agent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PyRLProto.Agent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PyRLAgent.Action)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 agentId = 1;</code>
     * @return The agentId.
     */
    int getAgentId();

    /**
     * <code>int32 buildingId = 2;</code>
     * @return The buildingId.
     */
    int getBuildingId();
  }
  /**
   * Protobuf type {@code PyRLAgent.Action}
   */
  public  static final class Action extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PyRLAgent.Action)
      ActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Action.newBuilder() to construct.
    private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Action() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Action();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Action(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              agentId_ = input.readInt32();
              break;
            }
            case 16: {

              buildingId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PyRLProto.internal_static_PyRLAgent_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PyRLProto.internal_static_PyRLAgent_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PyRLProto.Action.class, PyRLProto.Action.Builder.class);
    }

    public static final int AGENTID_FIELD_NUMBER = 1;
    private int agentId_;
    /**
     * <code>int32 agentId = 1;</code>
     * @return The agentId.
     */
    public int getAgentId() {
      return agentId_;
    }

    public static final int BUILDINGID_FIELD_NUMBER = 2;
    private int buildingId_;
    /**
     * <code>int32 buildingId = 2;</code>
     * @return The buildingId.
     */
    public int getBuildingId() {
      return buildingId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (agentId_ != 0) {
        output.writeInt32(1, agentId_);
      }
      if (buildingId_ != 0) {
        output.writeInt32(2, buildingId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (agentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, agentId_);
      }
      if (buildingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buildingId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PyRLProto.Action)) {
        return super.equals(obj);
      }
      PyRLProto.Action other = (PyRLProto.Action) obj;

      if (getAgentId()
          != other.getAgentId()) return false;
      if (getBuildingId()
          != other.getBuildingId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGENTID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentId();
      hash = (37 * hash) + BUILDINGID_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PyRLProto.Action parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.Action parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.Action parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.Action parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.Action parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PyRLProto.Action parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PyRLProto.Action parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PyRLProto.Action parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PyRLProto.Action parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PyRLProto.Action parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PyRLProto.Action parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PyRLProto.Action parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PyRLProto.Action prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PyRLAgent.Action}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PyRLAgent.Action)
        PyRLProto.ActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PyRLProto.internal_static_PyRLAgent_Action_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PyRLProto.internal_static_PyRLAgent_Action_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PyRLProto.Action.class, PyRLProto.Action.Builder.class);
      }

      // Construct using PyRLProto.Action.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        agentId_ = 0;

        buildingId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PyRLProto.internal_static_PyRLAgent_Action_descriptor;
      }

      @java.lang.Override
      public PyRLProto.Action getDefaultInstanceForType() {
        return PyRLProto.Action.getDefaultInstance();
      }

      @java.lang.Override
      public PyRLProto.Action build() {
        PyRLProto.Action result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PyRLProto.Action buildPartial() {
        PyRLProto.Action result = new PyRLProto.Action(this);
        result.agentId_ = agentId_;
        result.buildingId_ = buildingId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PyRLProto.Action) {
          return mergeFrom((PyRLProto.Action)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PyRLProto.Action other) {
        if (other == PyRLProto.Action.getDefaultInstance()) return this;
        if (other.getAgentId() != 0) {
          setAgentId(other.getAgentId());
        }
        if (other.getBuildingId() != 0) {
          setBuildingId(other.getBuildingId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PyRLProto.Action parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PyRLProto.Action) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int agentId_ ;
      /**
       * <code>int32 agentId = 1;</code>
       * @return The agentId.
       */
      public int getAgentId() {
        return agentId_;
      }
      /**
       * <code>int32 agentId = 1;</code>
       * @param value The agentId to set.
       * @return This builder for chaining.
       */
      public Builder setAgentId(int value) {
        
        agentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 agentId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgentId() {
        
        agentId_ = 0;
        onChanged();
        return this;
      }

      private int buildingId_ ;
      /**
       * <code>int32 buildingId = 2;</code>
       * @return The buildingId.
       */
      public int getBuildingId() {
        return buildingId_;
      }
      /**
       * <code>int32 buildingId = 2;</code>
       * @param value The buildingId to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingId(int value) {
        
        buildingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 buildingId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingId() {
        
        buildingId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PyRLAgent.Action)
    }

    // @@protoc_insertion_point(class_scope:PyRLAgent.Action)
    private static final PyRLProto.Action DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PyRLProto.Action();
    }

    public static PyRLProto.Action getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Action>
        PARSER = new com.google.protobuf.AbstractParser<Action>() {
      @java.lang.Override
      public Action parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Action(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Action> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Action> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PyRLProto.Action getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PyRLAgent_AgentInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PyRLAgent_AgentInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PyRLAgent_ActionInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PyRLAgent_ActionInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PyRLAgent_Agent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PyRLAgent_Agent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PyRLAgent_Action_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PyRLAgent_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017AgentInfo.proto\022\tPyRLAgent\"-\n\tAgentInf" +
      "o\022 \n\006agents\030\001 \003(\0132\020.PyRLAgent.Agent\"0\n\nA" +
      "ctionInfo\022\"\n\007actions\030\001 \003(\0132\021.PyRLAgent.A" +
      "ction\"J\n\005Agent\022\020\n\010agent_id\030\001 \001(\005\022\t\n\001x\030\002 " +
      "\001(\001\022\t\n\001y\030\003 \001(\001\022\r\n\005water\030\004 \001(\005\022\n\n\002hp\030\005 \001(" +
      "\005\"-\n\006Action\022\017\n\007agentId\030\001 \001(\005\022\022\n\nbuilding" +
      "Id\030\002 \001(\0052J\n\tPyRLAgent\022=\n\014getAgentInfo\022\025." +
      "PyRLAgent.ActionInfo\032\024.PyRLAgent.AgentIn" +
      "fo\"\000B\026\n\tPyRLAgentB\tPyRLProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PyRLAgent_AgentInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PyRLAgent_AgentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PyRLAgent_AgentInfo_descriptor,
        new java.lang.String[] { "Agents", });
    internal_static_PyRLAgent_ActionInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PyRLAgent_ActionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PyRLAgent_ActionInfo_descriptor,
        new java.lang.String[] { "Actions", });
    internal_static_PyRLAgent_Agent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PyRLAgent_Agent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PyRLAgent_Agent_descriptor,
        new java.lang.String[] { "AgentId", "X", "Y", "Water", "Hp", });
    internal_static_PyRLAgent_Action_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PyRLAgent_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PyRLAgent_Action_descriptor,
        new java.lang.String[] { "AgentId", "BuildingId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
